### ISSUE TITLE
Remove the authentication to non admin users and land them on the 3sixd home page without forcing them to sign in

### ISSUE THREAD

**Issue by godfreym** [Furaha/3sixd#12]
## Note:
Most of the users to this site but the recruiter are the not supposed to sign in in order to use the site so this issue will take care of that by adding the authentication **only** to those who needs to be authenticated like the recruiter/admin

## Story:
**AS A Non Admin User** of the site
**I WANT TO** be able to see the job openings, upload my CV and do all of the recruitment stuffs without having to sign up / sign in to the site
**SO THAT** I can skip all the harder part for having to sign in every time I want to use the site

**Comment by godfreym** [comment]
@arafatm Please Review by Providing some comments

**Comment by arafatm** [comment]
@godfreym what do you want me to comment on?

**Comment by godfreym** [comment]
@arafatm in case there is any comment, you told me on the last hangout, I quote "create some issues and let me know so I can comment on them"

**Comment by arafatm** [comment]
gotcha. Nope, looks good.

**Comment by godfreym** [comment]
cool

**Comment by godfreym** [comment]
@arafatm Done and demoed
