### ISSUE TITLE
The site contents should be customizable to allow different agencies to use the site with their own contents on the site views

### ISSUE THREAD

**Issue by godfreym** [Furaha/3sixd#5]
## Note from customer:

Let me give you both my thoughts briefly here, and if you'd like to be a part of the conversation Arafat I'm flexible, or as you said we'll just fill you in afterwards.   

Where I see this site going possibly, is as a service to offer other agencies.  So I'd like from the very beginning to think in those terms and not let the site get ahead of us where we'd need significant re-factoring later on.  With that in mind I'd like to move some of the content into config parameters where I can change the company name/address, the tag line, the about me text, the logo too I suppose.  For now that's all but we can continue to put things into tables with the idea it may not be 3sixD but another companies page later.  I assume an authentication layer would therefore be needed too so I can login and edit the config.  and possibly the design can be setup as a theme with more to come later (I'll be focusing a lot on content/devel not so much design as that's not my forte, but let's keep that in mind as well - and your input may be valuable here in terms of abstracting the look-n-feel however that's best done).

I want to keep it simple to start but designed for growth and additional features.  

And as always, please provide any opinions and ideas you may have on this.  I'll want other professional opinions all along.

## Story:

AS A Company/Agent using the 3sixD site
I WANT To be able to customize the site home view
SO THAT I can put my companies info on the site instead of using 3sixD infos

## Acceptance Criteria:
- [x] GIVEN I am the user accessing the 3sixD site WHEN I am using the site as an agent from another company apart from 3sixD THEN I SHOULD be able to customize the home view SO THAT I Can put my company's infos instead of 3sixd's info PR #4  & #6

**Comment by godfreym** [comment]
@arafatm This Issue is done

**Comment by arafatm** [comment]
@godfreym :+1:
